#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.

#apt-get install -y software-properties-common
#add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

# listen to web01 and web0
echo "
frontend abdeen_http
    bind *:80
    mode http
    default_backend abdeen_backend

backend abdeen_backend
    balance roundrobin
    server 360513-web-01 54.237.95.176:80 check
    server 360513-web-02 52.87.215.243:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
